# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the develop branch 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs: 
  # This workflow contains a single job called "build" 
  android-cpp: 
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      #- uses: actions/checkout@v2
      # Runs a single command using the runners shell 
     - uses: actions/checkout@v2 
      
     - run: |
            
            #  git push --delete  origin v1.0.2
            git describe --tags --abbrev=0
            
            #git tag -l
            #wget  -P /home/runner/work/android-cpp/android-cpp/.github/workflows/ "https://github.com/gerasymenkoke/android-cpp/releases/download/v1.0.2/hello"             
            #cd /home/runner/work/android-cpp/android-cpp/.github/workflows
            #pwd 
            #ls -l
            #chmod +x hello
            #./hello
            
           

