# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the develop branch 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs: 
   update_tag:
  # This workflow contains a single job called "build" 
      runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job 
      steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      #- uses: actions/checkout@v2
      # Runs a single command using the runners shell 
      - uses: actions/checkout@v2
      - name: build
        run: |
           cd /home/runner/work/android-cpp/android-cpp/.github/workflows
           pwd
           ls -l
           gcc hello.c -o hello
           pwd 
           ls -l
           chmod +x hello
           ./hello 
          # zip  -r site.zip  hello
           
     # - name: Download artifact
     #   uses: actions/download-artifact@v3
     #   with:
     #       name: site.zip 
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
            filename: hello.zip     
            exclusions: ' *.cpp / *.c /*.yml  / .git'  
               
      - name: Create new release
        id: create-new-release
        uses: actions/create-release@latest
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
                run_number
          draft: false
          prerelease: false     

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:  
         upload_url:  ${{ steps.create-new-release.outputs.upload_url }}
         asset_path: ./hello.zip
         asset_name: hello-v${{ github.run_number }}.zip
         asset_content_type: application/zip
    
            
      
    
