# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the develop branch 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs: 
  # This workflow contains a single job called "build" 
  android-cpp: 
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      #- uses: actions/checkout@v2
      # Runs a single command using the runners shell 
     - uses: actions/checkout@v2 
      
     - run: |
             #cd /home/runner/work/android-cpp/android-cpp/.github/workflows
             # chmod +x hello
             # rm ./hello
             pwd
             ls -l
     - name: Copy release URL into file
       run: |
         mkdir release
         printf "%s" "${{ steps.create_release.outputs.upload_url }}" > release/url.txt
     - name: Stash file containing the release URL as an artifact
       uses: actions/upload-release-asset@v1.0.2
       with:
        name: release/url.txt
        path: ./release
