# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the develop branch 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs: 
  # This workflow contains a single job called "build" 
  android-cpp: 
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      #- uses: actions/checkout@v2
      # Runs a single command using the runners shell 
     - uses: actions/checkout@v2 
      
     - run: |
             #cd /home/runner/work/android-cpp/android-cpp/.github/workflows
             # chmod +x hello
             # rm ./hello
             pwd
             ls -l
     - name: Copy release URL into file
       run: |
         mkdir release
         printf "%s" "${{ steps.create_release.outputs.upload_url }}" > release/url.txt
         cd /home/runner/work/android-cpp/android-cpp/release
         pwd
         ls -l
         cat url.txt
     - name: Stash file containing the release URL as an artifact
       uses: actions/upload-release-asset@v1.0.2
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          upload_url: "https://github.com/gerasymenkoke/android-cpp/releases/download/v1.0.2/hello"          
          #${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: "https://github.com/gerasymenkoke/android-cpp/releases/download/v1.0.2/hello"
          asset_name: "https://github.com/gerasymenkoke/android-cpp/releases/download/v1.0.2/hello"
          asset_content_type: application
