name: hello

on:
 pull_request:
   branches:
     -  'main'
 push: 
    branches: [ main ] 

jobs:
 hello:
   if: startsWith(github.head_ref,  'release/') == true
   name: Build hello
   runs-on: ubuntu-20.04
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-cpp@v1
       with: {cpp-version: 1.8}
     - name: Build release APK and AAB after test
       run: |
         ./gradlew hello
         ./gradlew assembleRelease
         ./gradlew bundleRelease
     - name: Upload APK
       uses: actions/upload-artifact@v2
       with:
         name: app-release.apk
         path: app/build/outputs/apk/release/app-release-unsigned.apk
     - name: Upload AAB Bundle
       uses: actions/upload-artifact@v2
       with:
         name: app-release.aab
         path: app/build/outputs/bundle/release/app-release.aab
